name: Deploy to SFTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Prepare deployment files
      run: |
        mkdir deploy
        # Copy your website files
        cp index.html deploy/
        cp responsive-nav.css deploy/
        cp responsive-nav.js deploy/
        cp script.js deploy/
        cp styles.css deploy/
        cp -r images/ deploy/
      
    - name: Deploy to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        protocol: sftp
        port: ${{ secrets.SFTP_PORT }}
        local-dir: './deploy/'
        server-dir: '/home/rainmaker/webapps/rainmaker/'
